apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo_pipe
  labels:
    app: todo_pipe 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo_pipe
  template:
    metadata:
      labels:
        app: todo_pipe
    spec:
      containers:
      - name: myproj
        image: namandocker101/todo_pipe
        ports:
        - containerPort: 80
