apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
spec:
  selector:
    app: todo-app  # Ensure this matches your Pod's labels
  ports:
    - protocol: TCP
      port: 80       # Expose on this port externally
      targetPort: 8000  # Port used by the container inside the Pod
      nodePort: 30001  # Optional: specify or let Kubernetes assign one
  type: NodePort
