apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
spec:
  selector:
    app: todo-app  # Ensure this matches your pod's label selector
  ports:
    - protocol: TCP
      port: 80       # Port your app is listening on inside the container
      targetPort: 8000  # Port your app is exposed on inside the container (as defined in the Dockerfile or deployment)
      nodePort: 30001  # Port exposed on each node for external access
  type: NodePort
